- name: "Copy original Ansible's inventory to /root"
  copy: src=/etc/ansible/hosts dest=/root/inventory_add_node remote_src=True
  tags: [ ocp_bastion_add_node ]

- name: "Read the content of this key"
  slurp: src=/root/.ssh/id_rsa.pub
  register: content_encoded
  tags: [ ocp_bastion_add_node ]

- name: "Reading Public Key generated. It's going to be copied to the entire cluster"
  set_fact: bastion_ssh_key="{{ content_encoded.content | b64decode }}"
  tags: [ ocp_bastion_add_node ]

- name: "Customize inventory 1/3: Adding a \"new_nodes\" into OSEv3:children section"
  lineinfile: path=/root/inventory_add_node state=present insertafter="^etcd" line="new_nodes"
  tags: [ ocp_bastion_add_node ]

- name: "Customize inventory 2/3: Creating a new section \"[new_nodes]\""
  lineinfile: path=/root/inventory_add_node state=present insertbefore="\[etcd\]" line="[new_nodes]\n"
  tags: [ ocp_bastion_add_node ]

- name: "Definition for this node: {{ node_name }}"
  set_fact: node_definition="{{ node_name }} openshift_node_group_name=node-config-compute"
  tags: [ ocp_bastion_add_node ]

- name: "Customize inventory 3/3: Adding a new definition for node {{ node_name }}"
  lineinfile: path=/root/inventory_add_node state=present insertafter="\[new_nodes\]" line="{{ node_definition }}"
  tags: [ ocp_bastion_add_node ]

- name: "Leave \"{{ node_name }}\" registered at the original inventory"
  lineinfile: path=/etc/ansible/hosts state=present insertafter="\[nodes\]" line="{{ node_definition }}"
  tags: [ ocp_bastion_add_node ]

- name: "Generating script to perform scaling up"
  template: src=add_node.sh.j2 dest=/root/add_node.sh mode=a+x force=True
  tags: [ ocp_bastion_add_node ]
